name: SAST - Semgrep Scan

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  semgrep:
    name: Run Semgrep SAST
    runs-on: ubuntu-latest

    permissions:
      security-events: write  # Pour uploader les r√©sultats SARIF
      contents: read

    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Semgrep scan
        run: semgrep scan --config=auto --sarif --output=semgrep.sarif --error

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
